site_name: Ultimate Terraform Bootcamp
docs_dir: chapters
plugins: 
  - search
pages:
  - Home: index.md
  - Getting Started with Terraform:
    - Setting up the environment: "00-environment-setup.md"
    - Important Commands: "02-terraform-important-commands.md"
    - Terraform Providers: "03-providers.md"
    - Resources: "04-resources.md"
    - Resource Dependencies: "05-resource-dependencies.md"
    - Input and Output Variables: "06-variables-and-outputs.md"
    - Provisioners in detail: "07-provisioners.md"
    - Data Sources: "08-datasources.md"
    - State Management in Terraform: "09-terraform-state.md"
    - Backend and Statelocking: "10-backends.md"
    - Course Outline: "XX-course-outline.md"
theme: readthedocs

